config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :house_features
  resources :features
  resources :types
  resources :houses 

  root 'houses#index'

end

app/models/house_feature.rb
class HouseFeature < ActiveRecord::Base
    belongs_to :house
    belongs_to :feature
end

app/controllers/house_features_controller.rb
class HouseFeaturesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_house_feature, only: [:show, :edit, :update, :destroy]

  # GET /house_features
  # GET /house_features.json
  def index
    @house_features = HouseFeature.all
  end

  # GET /house_features/1
  # GET /house_features/1.json
  def show
  end

  # GET /house_features/new
  def new
    @house_feature = HouseFeature.new
  end

  # GET /house_features/1/edit
  def edit
  end

  # POST /house_features
  # POST /house_features.json
  def create
    @house_feature = HouseFeature.new(house_feature_params)

    respond_to do |format|
      if @house_feature.save
        format.html { redirect_to @house_feature, notice: 'House feature was successfully created.' }
        format.json { render :show, status: :created, location: @house_feature }
      else
        format.html { render :new }
        format.json { render json: @house_feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /house_features/1
  # PATCH/PUT /house_features/1.json
  def update
    respond_to do |format|
      if @house_feature.update(house_feature_params)
        format.html { redirect_to @house_feature, notice: 'House feature was successfully updated.' }
        format.json { render :show, status: :ok, location: @house_feature }
      else
        format.html { render :edit }
        format.json { render json: @house_feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /house_features/1
  # DELETE /house_features/1.json
  def destroy
    @house_feature.destroy
    respond_to do |format|
      format.html { redirect_to house_features_url, notice: 'House feature was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house_feature
      @house_feature = HouseFeature.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_feature_params
      params.require(:house_feature).permit(:house_id, :feature_id)
    end
end

app/helpers/house_features_helper.rb
module HouseFeaturesHelper
end

app/views/house_features/_form.html.erb
<%= form_for(@house_feature) do |f| %>
  <% if @house_feature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@house_feature.errors.count, "error") %> prohibited this house_feature from being saved:</h2>

      <ul>
      <% @house_feature.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :house_id %><br>
    <%= f.number_field :house_id %>
  </div>
  <div class="field">
    <%= f.label :feature_id %><br>
    <%= f.number_field :feature_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/house_features/edit.html.erb
<h1>Editing House Feature</h1>

<%= render 'form' %>

<%= link_to 'Show', @house_feature %> |
<%= link_to 'Back', house_features_path %>

app/views/house_features/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing House Features</h1>

<table>
  <thead>
    <tr>
      <th>House</th>
      <th>Feature</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @house_features.each do |house_feature| %>
      <tr>
        <td><%= house_feature.house_id %></td>
        <td><%= house_feature.feature_id %></td>
        <td><%= link_to 'Show', house_feature %></td>
        <td><%= link_to 'Edit', edit_house_feature_path(house_feature) %></td>
        <td><%= link_to 'Destroy', house_feature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New House feature', new_house_feature_path %>

app/views/house_features/new.html.erb
<h1>New House Feature</h1>

<%= render 'form' %>

<%= link_to 'Back', house_features_path %>

app/views/house_features/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>House:</strong>
  <%= @house_feature.house_id %>
</p>

<p>
  <strong>Feature:</strong>
  <%= @house_feature.feature_id %>
</p>

<%= link_to 'Edit', edit_house_feature_path(@house_feature) %> |
<%= link_to 'Back', house_features_path %>