config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :house_features
  resources :features
  resources :types
  resources :houses 

  root 'houses#index'

end

app/models/house.rb
class House < ActiveRecord::Base
belongs_to :type
has_many :house_features, autosave: true
has_many :features, through: :house_features

    has_attached_file :photo, :styles => { :small => "150x150>" }, default_url: ""
                 
validates_attachment_presence :photo
validates_attachment_size :photo, :less_than => 5.megabytes
validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
validates :photo, presence: true
 validates :name, presence: true
   validates :name, length: { minimum: 2 }
   validates :name, length: { maximum: 20 }
   validates :name, uniqueness:{ case_sensitive: false }


   validates :name, length: { maximum: 200 }


end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_house, only: [:show, :edit, :update, :destroy]
  

  # GET /houses
  # GET /houses.json
  def index
  
     @q = House.ransack(params[:q])
       @houses = @q.result(distinct: true)

    
  else
    House.all
  end
  

  # GET /houses/1
  # GET /houses/1.json
  def show
     @types = Type.all
  end

  # GET /houses/new
  def new
    @house = House.new
  end
  
  

  # GET /houses/1/edit
  def edit
   
   @types = Type.all
  end

  # POST /houses
  # POST /houses.json
  def create
    @house = House.new(house_params)

    respond_to do |format|
      if @house.save
        format.html { redirect_to @house, notice: 'House was successfully created.' }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to @house, notice: 'House was successfully updated.' }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to houses_url, notice: 'House was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_params
      params.require(:house).permit(:photo, :name, :type_id, :type_ids, :q, { :feature_ids => [] }, :blurb)
    end
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/_form.html.erb
<%= form_for(@house) do |f| %>
  <% if @house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
      <% @house.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field"> 
   <%= f.label :name %> <br>
  <%= f.text_field :name %> <br>
  
  <%= f.label :type %><br>

  <%= f.select :type_id, 
    options_from_collection_for_select(Type.all, :id, :typename, @house.type_id) %><br>
 
 <div class="row">
     <%= f.label :features %><br>
       <ul class="checkbox-grid">
    <%= collection_check_boxes :house, :feature_ids, Feature.all, :id, :features do |b| %>
    <li class="collection-check-box">
          <%= b.check_box %>
          <%= b.label %>
        </li>
        <% end %>
</ul>
</div>
  <br>
 <%= f.label :blurb %> <br>
 <%= f.text_area :blurb,  size: "24x6" %>
   
    

  <br />



    <%= f.label :photo %><br>
    <%= f.text_field :photo %>
    
  
  </div>
  

 <%= f.file_field :photo %>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/houses/edit.html.erb
<h1>Editing House</h1>

<%= render 'form' %>

<%= link_to 'Show', @house %> |
<%= link_to 'Back', houses_path %>

app/views/houses/filters.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Houses</h1>

<table>
  <thead>
    <tr>
      <th>House</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @houses.each do |house| %>
      <tr>
       <td> <%= house.name %> </td>
       <td> <%= house.type_id %> </td>
        <td><%= link_to 'Show', house %></td>
        <td><%= link_to 'Edit', edit_house_path(house) %></td>
        <td><%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New House', new_house_path %>

app/views/houses/index.html.erb
<p id="notice"><%= notice %></p>
<br>
<h1>Find a House Package</h1>
<%= form_tag(houses_path, method: :get) do %>
 

<fieldset class="jumbotron">
  <legend>Search Our Database</legend>
  <%= search_form_for @q do |f| %>
 

    <div class="row"> 
     <%= f.label "Type" %><br>
    <ul class="checkbox-grid">
     
      <%= f.collection_check_boxes :type_id_in_any, Type.all, :id, :typename do |b| %>
        <li class="collection-check-box">
          <%= b.check_box %>
          <%= b.label %>
        </li>
      <% end %>
      </ul>
    </div>
    <br>
    <br>
    
        <div class="row">
      <%= f.label "Feature" %><br>
       <ul class="checkbox-grid">
      <%= f.collection_check_boxes :features_id_in_any, Feature.all, :id, :features do |b| %>
        <li class="collection-check-box">
          <%= b.check_box %>
          <%= b.label %>
        </li>
      <% end %>
      </ul>
    </div>

    <div class="actions"><%= f.submit "Search" %></div>
  <% end %>
</fieldset>
<% end %>



<table class="table table-hover" >
  <thead>
    <tr>
      <th>House Name </th>
      <th>Layout</th>
      <th>Type</th>
      <th>Features</th>
    </tr>
  </thead>

  <tbody>
    <% @houses.each do |house| %>
      <tr>
       <td> <%= house.name %> </td>
      <td> <%= image_tag house.photo.url(:small) %></td>
       <td> <%= house.type.typename %> </td>
       <td> <% house.features.each do |o| %>
            <%= o.features  %>
            <br>
            <%end %>
       
       </td>
        <td><%= link_to 'Show', house %></td>
        <%if user_signed_in? %>
        <td><%= link_to 'Edit', edit_house_path(house) %></td>
        <td><%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>
 <%if user_signed_in? %>
<%= link_to 'New House', new_house_path %> 
<% end %>

app/views/houses/new.html.erb
<h1>New House</h1>

<%= render 'form' %>

<%= link_to 'Back', houses_path %>

app/views/houses/show.html.erb
<p id="notice"><%= notice %></p>

 <div class="container">
  <div class="jumbotron">
    <h1> <%= @house.name %></h1>
    <p><%= @house.blurb %> </p>
  </div>

</div>
 
  

<div class='row'>
  <div class='col-md-4'>
  
    <%= image_tag @house.photo.url, class: 'img-fluid' %>
  
  </div>
  <div class='col-md-4'>
  <br>
  </div>
  <div class='col-md-4'>
  
    <h2> Features </h2>
    <% @house.features.each do |o| %>
            <%= o.features  %>
            <br>
            <%end %>
      <h2> Type </h2>
      <%= @house.type.typename %>
       
     
  </div>

</div>


<%= link_to 'Edit', edit_house_path(@house) %> |
<%= link_to 'Back', houses_path %>