config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :house_features
  resources :features
  resources :types
  resources :houses 

  root 'houses#index'

end

app/models/feature.rb
class Feature < ActiveRecord::Base
    has_many :house_features, autosave: true
    has_many :houses, through: :house_features

   validates :features, presence: true
   validates :features, length: { minimum: 2 }
   validates :features, length: { maximum: 50 }
   validates :features, uniqueness:{ case_sensitive: false }

end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_feature, only: [:show, :edit, :update, :destroy]

  # GET /features
  # GET /features.json
  def index
    @features = Feature.all
  end

  # GET /features/1
  # GET /features/1.json
  def show
  end

  # GET /features/new
  def new
    @feature = Feature.new
  end

  # GET /features/1/edit
  def edit
  end

  # POST /features
  # POST /features.json
  def create
    @feature = Feature.new(feature_params)

    respond_to do |format|
      if @feature.save
        format.html { redirect_to @feature, notice: 'Feature was successfully created.' }
        format.json { render :show, status: :created, location: @feature }
      else
        format.html { render :new }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /features/1
  # PATCH/PUT /features/1.json
  def update
    respond_to do |format|
      if @feature.update(feature_params)
        format.html { redirect_to @feature, notice: 'Feature was successfully updated.' }
        format.json { render :show, status: :ok, location: @feature }
      else
        format.html { render :edit }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /features/1
  # DELETE /features/1.json
  def destroy
    @feature.destroy
    respond_to do |format|
      format.html { redirect_to features_url, notice: 'Feature was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feature
      @feature = Feature.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feature_params
      params.require(:feature).permit(:features)
    end
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/views/features/_form.html.erb
<%= form_for(@feature) do |f| %>
  <% if @feature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feature.errors.count, "error") %> prohibited this feature from being saved:</h2>

      <ul>
      <% @feature.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :features %><br>
    <%= f.text_field :features %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/features/edit.html.erb
<h1>Editing Feature</h1>

<%= render 'form' %>

<%= link_to 'Show', @feature %> |
<%= link_to 'Back', features_path %>

app/views/features/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Features</h1>

<table>
  <thead>
    <tr>
      <th>Feature</th>
      <th>Houseid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @features.each do |feature| %>
      <tr>
        <td><%= feature.features %></td>
       
        <td><%= link_to 'Show', feature %></td>
        <td><%= link_to 'Edit', edit_feature_path(feature) %></td>
        <td><%= link_to 'Destroy', feature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feature', new_feature_path %>

app/views/features/new.html.erb
<h1>New Feature</h1>

<%= render 'form' %>

<%= link_to 'Back', features_path %>

app/views/features/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Feature:</strong>
  <%= @feature.features %>
</p>



<%= link_to 'Edit', edit_feature_path(@feature) %> |
<%= link_to 'Back', features_path %>